apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"firstpod","namespace":"landingspace"},"spec":{"containers":[{"args":["-c","while true; do echo Flag: $(landingspace); sleep 30; done"],"command":["/bin/bash"],"env":[{"name":"landingspace","valueFrom":{"configMapKeyRef":{"key":"landingspace-flag","name":"landingspace-configs"}}}],"image":"registry.merch.codes:5000/landingspace:latest","imagePullPolicy":"Always","name":"firstpod","volumeMounts":[{"mountPath":"/opt/secondspace","name":"landingspace-config-volume"},{"mountPath":"/opt/secondspace-deployments","name":"secondspace-deployments-volume"},{"mountPath":"/opt/secondspace-services","name":"secondspace-services-volume"},{"mountPath":"/opt/secondspace-ingresses","name":"secondspace-ingresses-volume"}]}],"restartPolicy":"Always","volumes":[{"configMap":{"defaultMode":420,"items":[{"key":"secondspace.kubeconfig","path":"secondspace.kubeconfig"}],"name":"landingspace-configs"},"name":"landingspace-config-volume"},{"configMap":{"defaultMode":420,"name":"secondspace-deployments"},"name":"secondspace-deployments-volume"},{"configMap":{"defaultMode":420,"name":"secondspace-services"},"name":"secondspace-services-volume"},{"configMap":{"defaultMode":420,"name":"secondspace-ingresses"},"name":"secondspace-ingresses-volume"}]}}
  creationTimestamp: "2024-02-19T19:20:58Z"
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          f:containers:
            k:{"name":"firstpod"}:
              .: {}
              f:args: {}
              f:command: {}
              f:env:
                .: {}
                k:{"name":"landingspace"}:
                  .: {}
                  f:name: {}
                  f:valueFrom:
                    .: {}
                    f:configMapKeyRef: {}
              f:image: {}
              f:imagePullPolicy: {}
              f:name: {}
              f:resources: {}
              f:terminationMessagePath: {}
              f:terminationMessagePolicy: {}
              f:volumeMounts:
                .: {}
                k:{"mountPath":"/opt/secondspace"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
                k:{"mountPath":"/opt/secondspace-deployments"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
                k:{"mountPath":"/opt/secondspace-ingresses"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
                k:{"mountPath":"/opt/secondspace-services"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
          f:dnsPolicy: {}
          f:enableServiceLinks: {}
          f:restartPolicy: {}
          f:schedulerName: {}
          f:securityContext: {}
          f:terminationGracePeriodSeconds: {}
          f:volumes:
            .: {}
            k:{"name":"landingspace-config-volume"}:
              .: {}
              f:configMap:
                .: {}
                f:defaultMode: {}
                f:items: {}
                f:name: {}
              f:name: {}
            k:{"name":"secondspace-deployments-volume"}:
              .: {}
              f:configMap:
                .: {}
                f:defaultMode: {}
                f:name: {}
              f:name: {}
            k:{"name":"secondspace-ingresses-volume"}:
              .: {}
              f:configMap:
                .: {}
                f:defaultMode: {}
                f:name: {}
              f:name: {}
            k:{"name":"secondspace-services-volume"}:
              .: {}
              f:configMap:
                .: {}
                f:defaultMode: {}
                f:name: {}
              f:name: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2024-02-19T19:20:58Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            k:{"type":"ContainersReady"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Initialized"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Ready"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:containerStatuses: {}
          f:hostIP: {}
          f:podIP: {}
          f:podIPs:
            .: {}
            k:{"ip":"10.42.1.7"}:
              .: {}
              f:ip: {}
          f:startTime: {}
      manager: k3s
      operation: Update
      subresource: status
      time: "2024-02-19T19:22:01Z"
  name: firstpod
  namespace: landingspace
  resourceVersion: "1820835"
  uid: 49db1ddf-419d-4dfe-9b12-bcb9793956da
spec:
  containers:
    - args:
        - -c
        - while true; do echo Flag: $(landingspace); sleep 30; done
      command:
        - /bin/bash
      env:
        - name: landingspace
          valueFrom:
            configMapKeyRef:
              key: landingspace-flag
              name: landingspace-configs
      image: registry.merch.codes:5000/landingspace:latest
      imagePullPolicy: Always
      name: firstpod
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /opt/secondspace
          name: landingspace-config-volume
        - mountPath: /opt/secondspace-deployments
          name: secondspace-deployments-volume
        - mountPath: /opt/secondspace-services
          name: secondspace-services-volume
        - mountPath: /opt/secondspace-ingresses
          name: secondspace-ingresses-volume
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-d9lqt
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k3s-server
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - configMap:
        defaultMode: 420
        items:
          - key: secondspace.kubeconfig
            path: secondspace.kubeconfig
        name: landingspace-configs
      name: landingspace-config-volume
    - configMap:
        defaultMode: 420
        name: secondspace-deployments
      name: secondspace-deployments-volume
    - configMap:
        defaultMode: 420
        name: secondspace-services
      name: secondspace-services-volume
    - configMap:
        defaultMode: 420
        name: secondspace-ingresses
      name: secondspace-ingresses-volume
    - name: kube-api-access-d9lqt
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: "2024-02-19T19:20:58Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2024-02-19T19:20:58Z"
      message: "containers with unready status: [firstpod]"
      reason: ContainersNotReady
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2024-02-19T19:20:58Z"
      message: "containers with unready status: [firstpod]"
      reason: ContainersNotReady
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2024-02-19T19:20:58Z"
      status: "True"
      type: PodScheduled
  containerStatuses:
    - image: registry.merch.codes:5000/landingspace:latest
      imageID: ""
      lastState: {}
      name: firstpod
      ready: false
      restartCount: 0
      started: false
      state:
        waiting:
          message: Back-off pulling image "registry.merch.codes:5000/landingspace:latest"
          reason: ImagePullBackOff
  hostIP: 10.3.3.10
  phase: Pending
  podIP: 10.42.1.7
  podIPs:
    - ip: 10.42.1.7
  qosClass: BestEffort
  startTime: "2024-02-19T19:20:58Z"
