#!/usr/bin/expect -f

# Copyright 2022 Carnegie Mellon University.
# Released under a MIT (SEI)-style license, please see LICENSE.md in the project 
# root or contact permission@sei.cmu.edu for full terms.

set timeout 10
spawn -noecho scp /home/user/Desktop/scripts/c1 guy@192.168.133.44:/home/guy/Public/
expect "ssword:"
send "n1c3Try\r"
expect eof
exit
