name: test-job

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: shared
    steps:
      - name: Run tests
        run: |
          echo "Running unit tests..."
          echo "Code coverage is 90%"
