[supervisord]
nodaemon=true
logfile=/var/log/supervisor/log.txt           
pidfile=/var/run/supervisord.pid

[program:sshd]
command=/usr/sbin/sshd -D -e -o LogLevel=INFO
autostart=true
autorestart=true
startsecs=1
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopsignal=TERM
autorestart=true

[program:tmc-ingest]
command=/usr/bin/python3 /app/ingest.py
directory=/app
autostart=true
autorestart=true
user=user
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0