events {
    worker_connections 1024; # cap connections per worker
}

http {
    # Docker embedded DNS
    resolver 127.0.0.11 valid=5s ipv6=off;

    # Retry behavior for all proxied backends
    proxy_next_upstream error timeout http_502 http_503 http_504;

    server {
        listen 80;
        server_name pawn.secondorder.pccc;

        location / {
            proxy_pass http://pawnshop.pccc:8080;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 80;
        server_name warehouse.secondorder.pccc;

        location / {
            proxy_pass http://warehouse.pccc:8080;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
