server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Forbid mutations.
    if ($request_method !~ ^(GET|HEAD)$) {
        return 405;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
