[libdefaults]
 default_realm = CTF.LOCAL
 dns_lookup_realm = false
 dns_lookup_kdc = false
 ticket_lifetime = 24h
 renew_lifetime = 7d
 forwardable = true
 pkinit_anchors = DIR:/etc/ssl/certs
 
[realms]
 CTF.LOCAL = {
  kdc = kdc.ctf.local
  admin_server = kdc.ctf.local
 }

[domain_realm]
 .ctf.local = CTF.LOCAL
 ctf.local = CTF.LOCAL
