[sssd]
services = nss, pam, sudo
config_file_version = 2
domains = ctf.local

[domain/ctf.local]
id_provider = ldap
auth_provider = krb5
chpass_provider = krb5
cache_credentials = True
enumerate = False

ldap_uri = ldap://ldap.ctf.local:389
ldap_search_base = dc=ctf,dc=local

krb5_realm = CTF.LOCAL
krb5_server = kdc.ctf.local

# sudo_provider = ldap
# ldap_sudo_search_base = ou=SUDOers,dc=ctf,dc=local

# Optional / helpful:
ldap_id_mapping = False
ldap_user_object_class = inetOrgPerson