x-challenge:
  name: "Daemon Hunter"
  description: |
    # Daemon Hunter

    A remote machine is running a daemon that has an open service. Gather any information you can find.

    **NICE Work Roles**

    - [Cyber Defense Analyst](https://niccs.cisa.gov/tools/nice-framework/)
    - [Exploitation Analyst](https://niccs.cisa.gov/tools/nice-framework/)

    **NICE Tasks**

    - [T0028](https://niccs.cisa.gov/tools/nice-framework/): Conduct and/or support authorized penetration testing on enterprise network assets.
    - [T0566](https://niccs.cisa.gov/tools/nice-framework/): Analyze internal operational architecture, tools, and procedures for ways to improve performance.


    ## Background

    A remote machine `vault` is running a service. You need to run tests and checks against the service and try to find as much information as you can from the service. You need to:

    1. Find the public token.
    1. Recover an encrypted token.
    1. Recover the runtime token.
    1. Decrypt the secret-file token.

    Your sources say that the following keywords are significant:

    - GETPUB
    - PEEKFILE
    - INFO
    - UPLOAD
    - CALL
    
    Known files on the target are:
    - secret_parts.h
    - symbols.txt
    - token_secret_file.enc

    ## Getting Started

    You are provided access to the standard Kali machine. The service accepts very specific and short commands.


    ## System and Tool Credentials

    |system/tool|username|password|
    |-----------|--------|--------|
    |kali|user|password|
    |vault|||
  summary: |
    A remote machine is running a daemon that has an open service. Gather any information you can find.

  templates:
    public_flag: &public_template "fake.bothify('PCCC{public_??_####}', letters='ABCDEF0123456789')"
    encrypted_flag: &encrypted_template "fake.bothify('PCCC{encrypted_??_####}', letters='ABCDEF0123456789')"
    runtime_flag: &runtime_template "fake.bothify('PCCC{runtime_??_####}', letters='ABCDEF0123456789')"
    secret_flag: &secret_template "fake.bothify('PCCC{secret_??_####}', letters='ABCDEF0123456789')"
  tags:
    - season:pc7
    - track:offense
    - round:finals
    - role:defensive-cybersecurity
    - role:exploitation-analyst
    - topics:reverse-engineering
    - topics:cryptography
  variables:
    
    public_flag:
      template: *public_template
      default: &public_template_default "PCCC{public_Got}"

    encrypted_flag:
      template: *encrypted_template
      default: &encrypted_template_default "PCCC{encrypted_Satisfied}"

    runtime_flag:
      template: *runtime_template
      default: &runtime_template_default "PCCC{runtime_Satisfied}"
    
    secret_flag:
      template: *secret_template
      default: &secret_template_default "PCCC{secret_Satisfied}"

  #total points 4140  
  questions:
    - name: "Question 1"
      body: "What is the public token value?"
      placeholder: "PCCC{token_value}"
      points: 828 #20%
      answer: *public_template_default
      max_attempts: 3

    - name: "Question 2"
      body: "What is the encrypted token value?"
      placeholder: "PCCC{token_value}"
      points: 828 #20%
      answer: *encrypted_template_default
      max_attempts: 3
      
    - name: "Question 3"
      body: "What is the runtime token value?"
      placeholder: "PCCC{token_value}"
      points: 1242 # 30%
      answer: *runtime_template_default
      max_attempts: 3
    
    - name: "Question 4"
      body: "What is the secret token value?"
      placeholder: "PCCC{token_value}"
      points: 1242 # 30%
      answer: *secret_template_default
      max_attempts: 3

services:
  vault:
    build: ./vault
    hostname: vault
    environment:
      publictoken: *public_template_default
      encryptedtoken: *encrypted_template_default
      runtimetoken: *runtime_template_default
      secrettoken: *secret_template_default
    networks:
      competitor_net:
  

networks:
  competitor_net:
    internal: true
    # external: true