#!/usr/bin/expect -f

# Copyright 2022 Carnegie Mellon University.
# Released under a MIT (SEI)-style license, please see LICENSE.md in the project 
# root or contact permission@sei.cmu.edu for full terms.

set timeout 10
spawn -noecho scp user@192.168.133.210:/home/user/Desktop/files/tf2 /home/guy/Documents/tf2
expect "ssword:"
send "sn3aky5ne@ki\r"
expect eof
exit
