-- MySQL Script generated by MySQL Workbench
-- Wed Jul 23 04:20:39 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema secondOrderWarehouse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema secondOrderWarehouse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `secondOrderWarehouse` DEFAULT CHARACTER SET utf8 ;
USE `secondOrderWarehouse` ;

-- -----------------------------------------------------
-- Table `secondOrderWarehouse`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secondOrderWarehouse`.`items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL,
  `description` TEXT NULL,
  `dropped_off` TINYINT NULL,
  `drop_off_date` DATETIME NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secondOrderWarehouse`.`documents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secondOrderWarehouse`.`documents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `item_id` INT NOT NULL,
  `filename` VARCHAR(100) NULL,
  `description` TEXT NULL,
  `metadata` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_documents_items_idx` (`item_id` ASC) VISIBLE,
  CONSTRAINT `fk_documents_items`
    FOREIGN KEY (`item_id`)
    REFERENCES `secondOrderWarehouse`.`items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secondOrderWarehouse`.`confirmed_pickups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secondOrderWarehouse`.`confirmed_pickups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `item_id` INT NOT NULL,
  `user_id` INT NULL,
  `name` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `date_of_pickup` DATETIME NULL,
  PRIMARY KEY (`id`, `item_id`),
  INDEX `fk_confirmed_pickups_items1_idx` (`item_id` ASC) VISIBLE,
  CONSTRAINT `fk_confirmed_pickups_items1`
    FOREIGN KEY (`item_id`)
    REFERENCES `secondOrderWarehouse`.`items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
