apiVersion: v1
kind: Service
metadata:
  name: postfix-service
  labels:
    service: postfix
spec:
  type: ClusterIP
  ports:
  - port: 25
    targetPort: 25
    protocol: TCP
    name: smtp
  - port: 587
    targetPort: 587
    protocol: TCP
    name: submission
  selector:
    service: postfix
