apiVersion: v1
kind: Service
metadata:
  name: roundcubemail-service
spec:
  type: ClusterIP
  selector:
    service: roundcubemail
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80

