#!/bin/bash

# Copyright 2022 Carnegie Mellon University.
# Released under a MIT (SEI)-style license, please see LICENSE.md in the project 
# root or contact permission@sei.cmu.edu for full terms.

set timeout 10
spawn -noecho ssh user@192.168.133.44 "sudo /lib/php/og"
expect "ssword:"
send "tartans\r"
expect eof
exit
