# Listen and bump TLS; reject non-TLS on :443
http_port 3128 ssl-bump \
  cert=/etc/squid/ca/ctf-proxy-ca.pem key=/etc/squid/ca/ctf-proxy-ca.key \
  generate-host-certificates=on dynamic_cert_mem_cache_size=4MB

# cert generator 
sslcrtd_program /usr/lib/squid/security_file_certgen -s /var/lib/ssl_db -M 4MB
sslcrtd_children 5


# ACLs
acl SSL_ports port 443 8443
acl CONNECT method CONNECT
http_access deny !CONNECT              # only CONNECT (TLS) method allowed
http_access deny CONNECT !SSL_ports    # only port 443 and 8443 allowed
http_access allow CONNECT SSL_ports  
http_access deny all                    # deny all other access 

# SSL bump
acl step1 at_step SslBump1
acl step2 at_step SslBump2
acl step3 at_step SslBump3

# Peek client hello and server certificate
ssl_bump peek step1
ssl_bump peek step2

# Define ACLs for specific OpenSSL errors
acl ssl_err_self_signed        ssl_error X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT
acl ssl_err_self_signed_chain  ssl_error X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN
acl ssl_err_unknown_issuer     ssl_error X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY
acl ssl_err_expired            ssl_error X509_V_ERR_CERT_HAS_EXPIRED
acl ssl_err_name_mismatch      ssl_error SQUID_X509_V_ERR_DOMAIN_MISMATCH
acl ssl_err_unable_verify      ssl_error X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE

# Certificate-validation policy
sslproxy_cert_error allow ssl_err_self_signed
sslproxy_cert_error allow ssl_err_self_signed_chain
sslproxy_cert_error allow ssl_err_unknown_issuer
sslproxy_cert_error allow ssl_err_unable_verify
sslproxy_cert_error deny  ssl_err_expired
sslproxy_cert_error deny  ssl_err_name_mismatch
sslproxy_cert_error deny  all

# After validation, splice (do not decrypt)
ssl_bump splice all


# Logging
access_log /var/log/squid/access.log squid
cache_log  /var/log/squid/cache.log
