apiVersion: v1
kind: Pod
metadata:
  name: python-tool
spec:
  containers:
  - name: python-tool
    image: cicirello/pyaction:latest
    command: ["/bin/bash", "/opt/script.sh"]
    imagePullPolicy: "IfNotPresent"
    volumeMounts:
    - name: python-tool-script
      mountPath: /opt/script.sh
      subPath: script.sh
  volumes:
    - name: python-tool-script
      configMap:
        name: python-tool-script
  restartPolicy: "Always"
