[libdefaults]
 default_realm = CTF.LOCAL
 dns_lookup_realm = false
 dns_lookup_kdc = false
 rdns = false
 ticket_lifetime = 24h
 renew_lifetime = 7d
 forwardable = true
[realms]
 CTF.LOCAL = {
  kdc = kdc.ctf.local
  admin_server = kdc.ctf.local
 }
[domain_realm]
 .ctf.local = CTF.LOCAL
 ctf.local = CTF.LOCAL
[logging]
  kdc = STDERR
  admin_server = STDERR
  default = STDERR