-- MySQL Script generated by MySQL Workbench
-- Tue Jul 22 22:29:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema secondOrderPawn
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema secondOrderPawn
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `secondOrderPawn` DEFAULT CHARACTER SET utf8 ;
USE `secondOrderPawn` ;

-- -----------------------------------------------------
-- Table `secondOrderPawn`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secondOrderPawn`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(10) NULL,
  `username` VARCHAR(100) NULL,
  `password` VARCHAR(255) NULL,
  `last_login` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secondOrderPawn`.`pawn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secondOrderPawn`.`pawn` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `description` TEXT NULL,
  `category` VARCHAR(100) NULL,
  `item_condition` VARCHAR(100) NULL,
  `price` FLOAT NULL,
  `image` VARCHAR(100) NULL,
  `listed_on` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secondOrderPawn`.`auctions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secondOrderPawn`.`auctions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `warehouse_id` INT NULL,
  `user_id` INT NOT NULL,
  `public` TINYINT(1) NOT NULL DEFAULT 0,
  `open` TINYINT(1) NOT NULL DEFAULT 0,
  `starting_bid` FLOAT NULL,
  `end_date` DATETIME NULL,
  `winner` INT NULL,
  `cover_image` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `warehouse_id_UNIQUE` (`warehouse_id` ASC) VISIBLE,
  INDEX `fk_auctions_users_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_auctions_users1_idx` (`winner` ASC) VISIBLE,
  CONSTRAINT `fk_auctions_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `secondOrderPawn`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auctions_users1`
    FOREIGN KEY (`winner`)
    REFERENCES `secondOrderPawn`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secondOrderPawn`.`bids`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secondOrderPawn`.`bids` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `auction_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `bid` FLOAT NULL,
  `timestamp` DATETIME NULL,
  PRIMARY KEY (`id`, `auction_id`, `user_id`),
  INDEX `fk_bids_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_bids_auctions1_idx` (`auction_id` ASC) VISIBLE,
  CONSTRAINT `fk_bids_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `secondOrderPawn`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bids_auctions1`
    FOREIGN KEY (`auction_id`)
    REFERENCES `secondOrderPawn`.`auctions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secondOrderPawn`.`alerts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secondOrderPawn`.`alerts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `auction_id` INT NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`, `auction_id`),
  INDEX `fk_alerts_auctions1_idx` (`auction_id` ASC) VISIBLE,
  CONSTRAINT `fk_alerts_auctions1`
    FOREIGN KEY (`auction_id`)
    REFERENCES `secondOrderPawn`.`auctions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secondOrderPawn`.`cancellations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secondOrderPawn`.`cancellations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `auction_id` INT NOT NULL,
  `reason` TEXT NULL,
  `approved` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `auction_id`),
  INDEX `fk_cancellations_auctions1_idx` (`auction_id` ASC) VISIBLE,
  CONSTRAINT `fk_cancellations_auctions1`
    FOREIGN KEY (`auction_id`)
    REFERENCES `secondOrderPawn`.`auctions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secondOrderPawn`.`pickups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secondOrderPawn`.`pickups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `item_id` INT NOT NULL,
  `auction_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `item_id`),
  INDEX `fk_pickups_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_pickups_auctions1_idx` (`auction_id` ASC) VISIBLE,
  CONSTRAINT `fk_pickups_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `secondOrderPawn`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pickups_auctions1`
    FOREIGN KEY (`auction_id`)
    REFERENCES `secondOrderPawn`.`auctions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
